name: app_baru
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  get: ^4.6.6
  firebase_auth: ^4.17.6
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.15.6
  test_api: ^0.6.1
  flutterfire_cli: ^0.1.1+2
  firebase_storage: ^11.6.6
  flutter_login: ^5.0.0
  cli_util: ^0.3.5  
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/Logo.png
