// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhx1Z6sMTdt5evRTRkpCwuCnhyruLpuAU',
    appId: '1:833293219500:web:6e78cca20d221522d11109',
    messagingSenderId: '833293219500',
    projectId: 'appbaru-1e97c',
    authDomain: 'appbaru-1e97c.firebaseapp.com',
    storageBucket: 'appbaru-1e97c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF__UD7rrsuJQ54bRPDIQNtQDJzL32w8M',
    appId: '1:833293219500:android:2268bbc50adfc792d11109',
    messagingSenderId: '833293219500',
    projectId: 'appbaru-1e97c',
    storageBucket: 'appbaru-1e97c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6XdLNYfqrQwITQmY3BBQQBKFhWs3PSA',
    appId: '1:833293219500:ios:69d18e97596fa7e2d11109',
    messagingSenderId: '833293219500',
    projectId: 'appbaru-1e97c',
    storageBucket: 'appbaru-1e97c.appspot.com',
    iosBundleId: 'com.Ap.appBaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6XdLNYfqrQwITQmY3BBQQBKFhWs3PSA',
    appId: '1:833293219500:ios:9f8dd8ed8228c2d8d11109',
    messagingSenderId: '833293219500',
    projectId: 'appbaru-1e97c',
    storageBucket: 'appbaru-1e97c.appspot.com',
    iosBundleId: 'com.Ap.appBaru.RunnerTests',
  );
}
